/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as propertyFactorySol from "./PropertyFactory.sol";
export type { propertyFactorySol };
export type { LuxePropertyShare } from "./LuxePropertyShare";
