# Generated by Django 5.2.11 on 2026-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_location_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(),
        ),
    ]
