# Generated by Django 5.2.11 on 2026-02-04 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='property',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
