# Generated by Django 5.2.11 on 2026-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='is_processed',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
