# Generated by Django 5.2.11 on 2026-02-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_inquiry_is_processed_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
    ]
