# Generated by Django 5.2.11 on 2026-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_inquiry_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default='', upload_to='property_gallery/'),
            preserve_default=False,
        ),
    ]
