# Generated by Django 5.2.11 on 2026-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_agent_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
