/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as propertyFactorySol from "./PropertyFactory.sol";
export { LuxePropertyShare__factory } from "./LuxePropertyShare__factory";
